name: 📜 Draft Release Notes

on:
  push:
    branches: [ main ]

jobs:

  draft:
    name: 📜 Draft Release Notes
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, '🚀') }}
    steps:

      - uses: release-drafter/release-drafter@v5
        id: release_notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
